//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thai.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thai.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _252295835_609841426825323_1408735021841395939_n {
            get {
                object obj = ResourceManager.GetObject("252295835_609841426825323_1408735021841395939_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _252295835_609841426825323_1408735021841395939_n1 {
            get {
                object obj = ResourceManager.GetObject("252295835_609841426825323_1408735021841395939_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _286887019_3231318887151607_1189587858709077926_n {
            get {
                object obj = ResourceManager.GetObject("286887019_3231318887151607_1189587858709077926_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _286887019_3231318887151607_1189587858709077926_n1 {
            get {
                object obj = ResourceManager.GetObject("286887019_3231318887151607_1189587858709077926_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _286887019_3231318887151607_1189587858709077926_n2 {
            get {
                object obj = ResourceManager.GetObject("286887019_3231318887151607_1189587858709077926_n2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _287212574_1248742912536378_2901309944621164897_n {
            get {
                object obj = ResourceManager.GetObject("287212574_1248742912536378_2901309944621164897_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _287854587_462143562383437_5650731066332268285_n {
            get {
                object obj = ResourceManager.GetObject("287854587_462143562383437_5650731066332268285_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _287854587_462143562383437_5650731066332268285_n1 {
            get {
                object obj = ResourceManager.GetObject("287854587_462143562383437_5650731066332268285_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _287906129_547820616889862_1337748662245801417_n {
            get {
                object obj = ResourceManager.GetObject("287906129_547820616889862_1337748662245801417_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _287906129_547820616889862_1337748662245801417_n1 {
            get {
                object obj = ResourceManager.GetObject("287906129_547820616889862_1337748662245801417_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _287907181_453458849935815_5115353919395428635_n {
            get {
                object obj = ResourceManager.GetObject("287907181_453458849935815_5115353919395428635_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _287907181_453458849935815_5115353919395428635_n1 {
            get {
                object obj = ResourceManager.GetObject("287907181_453458849935815_5115353919395428635_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _287920647_735794771207820_678908212291940289_n {
            get {
                object obj = ResourceManager.GetObject("287920647_735794771207820_678908212291940289_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _287920647_735794771207820_678908212291940289_n1 {
            get {
                object obj = ResourceManager.GetObject("287920647_735794771207820_678908212291940289_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _287920647_735794771207820_678908212291940289_n2 {
            get {
                object obj = ResourceManager.GetObject("287920647_735794771207820_678908212291940289_n2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _287933051_584259466649640_2502455368170713214_n {
            get {
                object obj = ResourceManager.GetObject("287933051_584259466649640_2502455368170713214_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _287933051_584259466649640_2502455368170713214_n1 {
            get {
                object obj = ResourceManager.GetObject("287933051_584259466649640_2502455368170713214_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288147237_422240386434068_8706997685319803072_n {
            get {
                object obj = ResourceManager.GetObject("288147237_422240386434068_8706997685319803072_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288147237_422240386434068_8706997685319803072_n1 {
            get {
                object obj = ResourceManager.GetObject("288147237_422240386434068_8706997685319803072_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288147237_422240386434068_8706997685319803072_n2 {
            get {
                object obj = ResourceManager.GetObject("288147237_422240386434068_8706997685319803072_n2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288163110_738384690784881_2499296862077075065_n {
            get {
                object obj = ResourceManager.GetObject("288163110_738384690784881_2499296862077075065_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288163110_738384690784881_2499296862077075065_n1 {
            get {
                object obj = ResourceManager.GetObject("288163110_738384690784881_2499296862077075065_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288163110_738384690784881_2499296862077075065_n2 {
            get {
                object obj = ResourceManager.GetObject("288163110_738384690784881_2499296862077075065_n2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288398190_409728771075430_6789514093553388977_n {
            get {
                object obj = ResourceManager.GetObject("288398190_409728771075430_6789514093553388977_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288442998_1376772082818367_501589787953775157_n {
            get {
                object obj = ResourceManager.GetObject("288442998_1376772082818367_501589787953775157_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288479968_2164210200440148_2587505452116949922_n {
            get {
                object obj = ResourceManager.GetObject("288479968_2164210200440148_2587505452116949922_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288479968_2164210200440148_2587505452116949922_n1 {
            get {
                object obj = ResourceManager.GetObject("288479968_2164210200440148_2587505452116949922_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288493087_1945812612275681_4907534636938753131_n {
            get {
                object obj = ResourceManager.GetObject("288493087_1945812612275681_4907534636938753131_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288493087_1945812612275681_4907534636938753131_n1 {
            get {
                object obj = ResourceManager.GetObject("288493087_1945812612275681_4907534636938753131_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288674988_724397092122235_2522966597829451010_n {
            get {
                object obj = ResourceManager.GetObject("288674988_724397092122235_2522966597829451010_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288723866_1095473381069253_180562388623836639_n {
            get {
                object obj = ResourceManager.GetObject("288723866_1095473381069253_180562388623836639_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288723866_1095473381069253_180562388623836639_n1 {
            get {
                object obj = ResourceManager.GetObject("288723866_1095473381069253_180562388623836639_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288728648_973977846618280_6715682761272686802_n {
            get {
                object obj = ResourceManager.GetObject("288728648_973977846618280_6715682761272686802_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288728648_973977846618280_6715682761272686802_n1 {
            get {
                object obj = ResourceManager.GetObject("288728648_973977846618280_6715682761272686802_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288834530_756147389153011_775682893963131792_n {
            get {
                object obj = ResourceManager.GetObject("288834530_756147389153011_775682893963131792_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288889909_400011752180367_7232129452881811648_n {
            get {
                object obj = ResourceManager.GetObject("288889909_400011752180367_7232129452881811648_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288989607_1427641211013682_6597746084046733690_n {
            get {
                object obj = ResourceManager.GetObject("288989607_1427641211013682_6597746084046733690_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288991221_1180712322769751_4449318448500233535_n {
            get {
                object obj = ResourceManager.GetObject("288991221_1180712322769751_4449318448500233535_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288991221_1180712322769751_4449318448500233535_n1 {
            get {
                object obj = ResourceManager.GetObject("288991221_1180712322769751_4449318448500233535_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288991221_1180712322769751_4449318448500233535_n2 {
            get {
                object obj = ResourceManager.GetObject("288991221_1180712322769751_4449318448500233535_n2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288996048_1090966331845334_4963080263432494697_n {
            get {
                object obj = ResourceManager.GetObject("288996048_1090966331845334_4963080263432494697_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288999211_347116617504196_2753257891870552547_n {
            get {
                object obj = ResourceManager.GetObject("288999211_347116617504196_2753257891870552547_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _288999211_347116617504196_2753257891870552547_n1 {
            get {
                object obj = ResourceManager.GetObject("288999211_347116617504196_2753257891870552547_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _289020604_2203952806437925_7947640387112357643_n {
            get {
                object obj = ResourceManager.GetObject("289020604_2203952806437925_7947640387112357643_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _289271727_3095997600617478_7457706838748559098_n {
            get {
                object obj = ResourceManager.GetObject("289271727_3095997600617478_7457706838748559098_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _986bdd81b21c8f044cad48ef37b94539 {
            get {
                object obj = ResourceManager.GetObject("986bdd81b21c8f044cad48ef37b94539", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f14 {
            get {
                object obj = ResourceManager.GetObject("f14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f3 {
            get {
                object obj = ResourceManager.GetObject("f3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap food___beverage {
            get {
                object obj = ResourceManager.GetObject("food & beverage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap food___beverage__1_ {
            get {
                object obj = ResourceManager.GetObject("food & beverage (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap food___beverage__1_1 {
            get {
                object obj = ResourceManager.GetObject("food & beverage (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap food___beverage__1_2 {
            get {
                object obj = ResourceManager.GetObject("food & beverage (1)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap food___beverage__1_3 {
            get {
                object obj = ResourceManager.GetObject("food & beverage (1)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap food___beverage__2_ {
            get {
                object obj = ResourceManager.GetObject("food & beverage (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap food___beverage__2_1 {
            get {
                object obj = ResourceManager.GetObject("food & beverage (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap food___beverage__2_2 {
            get {
                object obj = ResourceManager.GetObject("food & beverage (2)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap food___beverage__3_ {
            get {
                object obj = ResourceManager.GetObject("food & beverage (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap food___beverage__3_1 {
            get {
                object obj = ResourceManager.GetObject("food & beverage (3)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap food___beverage__3_2 {
            get {
                object obj = ResourceManager.GetObject("food & beverage (3)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FRK2381 {
            get {
                object obj = ResourceManager.GetObject("FRK2381", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lay_Thai_res {
            get {
                object obj = ResourceManager.GetObject("Lay Thai res", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lay_Thai_res1 {
            get {
                object obj = ResourceManager.GetObject("Lay Thai res1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Laythai_restaurant {
            get {
                object obj = ResourceManager.GetObject("Laythai restaurant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap left_arrow_in_circular_button_black_symbol {
            get {
                object obj = ResourceManager.GetObject("left-arrow-in-circular-button-black-symbol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pay {
            get {
                object obj = ResourceManager.GetObject("Pay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pay__1_ {
            get {
                object obj = ResourceManager.GetObject("Pay (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pay__2_ {
            get {
                object obj = ResourceManager.GetObject("Pay (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pay__2_1 {
            get {
                object obj = ResourceManager.GetObject("Pay (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pay__3_ {
            get {
                object obj = ResourceManager.GetObject("Pay (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pay__4_ {
            get {
                object obj = ResourceManager.GetObject("Pay (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap restaurant_in_valkenswaard {
            get {
                object obj = ResourceManager.GetObject("restaurant-in-valkenswaard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unlimited_Pasta_Fest_ {
            get {
                object obj = ResourceManager.GetObject("Unlimited Pasta Fest!", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unlimited_Pasta_Fest___1_ {
            get {
                object obj = ResourceManager.GetObject("Unlimited Pasta Fest! (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unlimited_Pasta_Fest___2_ {
            get {
                object obj = ResourceManager.GetObject("Unlimited Pasta Fest! (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unlimited_Pasta_Fest___2_1 {
            get {
                object obj = ResourceManager.GetObject("Unlimited Pasta Fest! (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unlimited_Pasta_Fest___3_ {
            get {
                object obj = ResourceManager.GetObject("Unlimited Pasta Fest! (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ดีไซน์ที่ไม่มีชื่อ {
            get {
                object obj = ResourceManager.GetObject("ดีไซน์ที่ไม่มีชื่อ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ดีไซน์ที่ไม่มีชื่อ__1_ {
            get {
                object obj = ResourceManager.GetObject("ดีไซน์ที่ไม่มีชื่อ (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ดีไซน์ที่ไม่มีชื่อ__2_ {
            get {
                object obj = ResourceManager.GetObject("ดีไซน์ที่ไม่มีชื่อ (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ดีไซน์ที่ไม่มีชื่อ__2_1 {
            get {
                object obj = ResourceManager.GetObject("ดีไซน์ที่ไม่มีชื่อ (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ดีไซน์ที่ไม่มีชื่อ_1_ {
            get {
                object obj = ResourceManager.GetObject("ดีไซน์ที่ไม่มีชื่อ(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ดีไซน์ที่ไม่มีชื่อ1 {
            get {
                object obj = ResourceManager.GetObject("ดีไซน์ที่ไม่มีชื่อ1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ดีไซน์ที่ไม่มีชื่อ2 {
            get {
                object obj = ResourceManager.GetObject("ดีไซน์ที่ไม่มีชื่อ2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ดีไซน์ที่ไม่มีชื่อ3 {
            get {
                object obj = ResourceManager.GetObject("ดีไซน์ที่ไม่มีชื่อ3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ดีไซน์ที่ไม่มีชื่อ4 {
            get {
                object obj = ResourceManager.GetObject("ดีไซน์ที่ไม่มีชื่อ4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ดีไซน์ที่ไม่มีชื่อ5 {
            get {
                object obj = ResourceManager.GetObject("ดีไซน์ที่ไม่มีชื่อ5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
